version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@enkidevs/eslint-config-frontend"
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.14
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
